anct-cnum/portail-backoffice

.env, src/actions/conseiller.actions.js, src/actions/index.js, src/components/connected/structure/index.js, src/reducers/conseillersReducer.js, src/reducers/rootReducer.js, src/services/conseiller.service.js, src/services/user.service.js
Ne compile pas ... ! Manque la PR qui va arriver de Sébastien
=> ajout de la connexion API pour la liste des conseillers

.gitignore, package-lock.json, package.json, src/index.html, webpack.config.js
Pour éviter les pbs de cache des assets css et js
=> ajout hash nom bundles css et js et integration aux scripts run

src/components/anonymous/Login.js, src/components/common/Header.js, src/components/connected/admin/Documents.js, src/components/connected/admin/Menu.js, src/components/connected/admin/Structures.js, src/components/connected/admin/index.js
Ajustement Page Login et du header (déconnexion, design...) en fonction des roles + ajout de la rubrique docs
=> ajout doc prefet et reglage page login et header

src/components/connected/admin/Stats.js
=> ajout statistiques matchings sur admin

src/components/connected/admin/ExportsCoselec.js, src/components/connected/admin/Menu.js, src/components/connected/admin/index.js, src/services/exports.service.js
Il y a toute une bidouille sur les liens pour ajouter l'en-tête d'autorisation
=> ajout des exports sur l'admin

src/components/common/SearchBox.js
dont celle du pavé numérique
bouton du pavé numérique :
code: NumpadEnter,
charCode: 13,
key: Enter,
keyCode: 13,
ENTER principal :
code: Enter,
charCode: 13,
key: Enter,
keyCode: 13,
=> Pour supporter toutes les touches ENTER

src/reducers/filterDateReducer.js
Date de début au 17 novembre 2020
=> quick fix pour init la bonne date de début

src/components/connected/admin/StructureDetails.js, src/components/connected/admin/Structures.js
Correction du wording des champs au singulier
=> Correction wording detail structure

assets/css/style.scss, src/App.js, src/actions/user.actions.js, src/components/anonymous/ForgottenPassword.js, src/components/anonymous/Login.js, src/components/anonymous/createAccount/ChoosePassword.js, src/reducers/motDePasseOublieReducer.js, src/reducers/rootReducer.js, src/services/user.service.js
=> Page mot de passe oublié

src/components/connected/structure/index.js
J'ai remarqué que le script était appelé à chaque fois qu'on clique sur une page.
=> Faire une seule initialisation

src/components/connected/admin/Structure.js, src/components/connected/admin/StructureDetails.js, src/components/connected/structure/ConseillerDetails.js, src/components/connected/structure/index.js, src/reducers/conseillerReducer.js
Reste juste à modifier le nombreConseillersCoselec affiché quand on aura la fonction de calcul
=> Block recrutee limit

src/actions/conseiller.actions.js, src/components/connected/structure/ButtonsAction.js, src/components/connected/structure/ConseillerDetails.js, src/components/connected/structure/ConseillerNonMisEnRelation.js, src/reducers/conseillerReducer.js
Je n'arrive pas à récupérer la mise en relation.
=> Clique sur Pré sélectionner

src/components/connected/structure/Conseiller.js
Reverts anct-cnum/portail-backoffice#167
=> Revert "fix affichage logo pix dans tableau sa"

assets/css/style.scss, src/components/connected/structure/ButtonsAction.js, src/components/connected/structure/Demarches.js, src/components/connected/structure/popins/popinConfirmationAnnulation.js, src/components/connected/structure/popins/popinRecrutee.js
Et correction texte workflow recrutement
=> Ajout de popin annulation 

src/components/connected/admin/StructureDetails.js
=> Rectification "statutsLabel" pour les statuts "finalisee_non_disponible"

src/components/connected/structure/Conseiller.js, src/components/connected/structure/ConseillerNonMisEnRelation.js
=> Ajouter dans la colonne "statut" : l'information "candidat déjà recruté" lorsque le candidat est recruté.

src/actions/user.actions.js
En lien avec ce ticket Trello => https://trello.com/c/Tn1ue9Xn
=> Prendre en compte les utilisateurs qui ont plusieurs rôles sur le mécanisme de changement de mot de passe

src/components/connected/admin/StructureDetails.js, src/reducers/structureReducer.js
Nettoyage du SIRET et du nom de la structure précédemment validée
=> nettoyage du message de la validation précédente

src/components/connected/structure/Recrutements.js
Suite à cette remonter sur crisp => https://app.crisp.chat/website/ea669e13-e40f-40c8-be23-e43565c0e62c/inbox/session_0a5769a1-8b1c-46c5-9267-fa84763af437/
=> fix sur l'onglet "Mes recrutements"

src/components/connected/admin/ConseillerDetails.js, src/components/connected/admin/StructureDetails.js
- Liens vers les pages détails des candidats validés et recrutés
=> - Affichage de la liste des candidats validés

src/components/connected/admin/Structures.js
changement du nom de la colonne candidature pour statut dans la liste des structures
=> changement du nom de la colonne candidature => statut

src/components/connected/admin/Documents.js
ajout des éléments de communication dans l'onglet mes documents de l'espace préfet
=> ajout des éléments de communication (espace préfet)

src/components/connected/admin/Menu.js
ajout de l'onglet Données de déploiement des CnFS dans l'espace préfet qui permet d'accéder au métabase
=> ajout de l'onglet Données de déploiement des CnFS

assets/css/style.scss, src/components/connected/structure/Pilotage.js
=> Ajout du lien vers le guide coop

src/components/connected/admin/statistiques/BottomPage.js, src/components/connected/admin/statistiques/Components/ElementHighcharts.js
=> Statistiques prefet: style pour usagers réorientés

src/components/connected/admin/StructureDetails.js
=> Ajout du statut Nouvelle Rupture dans les stats sur la page détails
